:global:
  componentName: Argo CD
  githubUrl: https://github.com/projectsyn/component-argocd
  feature_goUnitTests: false
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - openshift
      - params

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
