= Parameters

The parent key for all of the following parameters is `argocd`.


== `namespace`

[horizontal]
type:: string
default:: `syn`

The namespace in which to deploy this component.

== `distribution`

[horizontal]
type:: string
default:: ${facts:distribution}

The Kubernetes distribution of the cluster.

=== `resync_seconds`

[horizontal]
type:: int
default:: `180`

Resync interval in seconds.
Lower values mean quicker sync but higher CPU usage and more Git traffic.

=== `ssh_known_hosts`

[horizontal]
type:: string

SSH known hosts for Git servers.

== `images`

[horizontal]
type:: dictionary

Dictionary containing the container images used by this component.

[NOTE]
The tag for the ArgoCD image is used to download the corresponding deployment manifests.

== `log_level.default`

[horizontal]
type:: string
default:: `info`

The default log level for all ArgoCD components.

[NOTE]
By using the `log_level.[component]` parameter, you can override the default log level for a specific component. `[component]` can be one of `server`, `application_controller` or `repo_server`.

== `log_format.default`

[horizontal]
type:: string
default:: `text`

The default log format for all ArgoCD components.

[NOTE]
By using the `log_format.[component]` parameter, you can override the default log format for a specific component. `[component]` can be one of `server`, `application_controller` or `repo_server`.

== `resources`

[horizontal]
type:: dictionary
defaults:: https://github.com/projectsyn/component-argocd/blob/master/class/defaults.yml[See `class/defaults.yml`]

Dictionary containing the resource requests and limits for the different
components. Keys correspond to different pods/containers:

* `application_controller`
* `redis`
* `repo_server`
* `repo_server_vault_agent` - for the `vault_agent` container in the `repo-server` pod
* `server`

Users can remove configured requests and limits by setting any keys or subkeys in the dictionary to `null`.


== `monitoring.enabled`

[horizontal]
type:: bool
default:: `true`

If monitoring should be enabled for this component.
Requires the https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator] to be installed.

== `monitoring.dashboards`

[horizontal]
type:: bool
default:: `true`

If dashboards should be enabled for this component.
Requires the https://github.com/integr8ly/grafana-operator[Grafana Operator] to be installed.

== `monitoring.prometheus_rule_labels`

[horizontal]
type:: dict
default:: `{"prometheus":"platform"}`

Labels to set on the alert rule configuration.
Can be used to ensure prometheus-operator picks up the `PrometheusRule` object by setting appropriate labels.


== Example

[source,yaml]
----
parameters:
  argocd:
    resync_seconds: 3
    ssh_known_hosts: |
      git.example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO9EkPcVdsz/oVTI2VJkBlq8Mv/dg3rhcbgzAEKyiwUG
    monitoring:
      dashboards: true
----
